language: haskell
os:
  - linux
  # - osx
addons:
  apt:
    packages:
      - c2hs
      - libopenmpi-dev
      - openmpi-bin
    update: true
ghc:
  # - "7.10"
  # - "8.0"
  # - "8.2"
  - "8.4"
notifications:
  email: false

# script:
#   - cabal configure --enable-tests && cabal build && cabal test

# install:
#   - cabal install --only-dependencies --enable-tests
